version: '3.8'

services:
  nginx:
    container_name: nginx
    volumes:
      - angular-vol:/var/www/angular
    networks:
      - eventify
    depends_on:
      - angular
    build:
      context: nginx
      dockerfile: Dockerfile
      args:
        CERT_FILE: $CERT_FILE
        KEY_FILE: $KEY_FILE
        CERTS_: $CERTS_
        KEYS_: $KEYS_
    env_file: .env
    ports:
      - "$CLIENT_IP:$CLIENT_PORT:$CLIENT_PORT"
    restart: on-failure

  postgres:
    image: postgres:alpine
    container_name: postgres
    networks:
      - eventify
    env_file: .env
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    restart: unless-stopped
    expose:
      - $POSTGRES_PORT

  angular:
    container_name: angular
    env_file: .env
    volumes:
      - angular-vol:/app/dist/my_app
    networks:
      - eventify
    build:
      context: angular
      dockerfile: Dockerfile
      args:
        SERVER_IP: $SERVER_IP
        SERVER_PORT: $SERVER_PORT
        SERVER_PROT: $SERVER_PROT
    depends_on:
      - springboot
    restart: on-failure

  springboot:
    container_name: springboot
    networks:
      - eventify
    depends_on:
      - postgres
    build:
      context: springboot
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "$SERVER_IP:$SERVER_PORT:$SERVER_PORT"
    restart: on-failure

volumes:
  postgres-vol:
  angular-vol:

networks:
  eventify:
    driver: bridge
